"""
Topic: HashTable, String, BitManipulation, Sorting
Difficulty: Easy

Question: 389. Find the Difference
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Path: solutions/FindTheDifference(389).py  

"""

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        S=list(s) 
        T=list(t)
        for i in range(0,len(T)):
            if T[i] in S: 
                S.remove(T[i])
            else: 
                return T[i]